[window]
opacity = 0.9
blur = true
startup_mode = "Maximized"
dynamic_title = true
decorations_theme_variant = "Dark"
[font]
normal = { family = "Fira Code Retina", style = "Retina" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code Light", style = "Italic" }
bold_italic = { family = "Fira Code SemiBold", style = "Italic" }
size = 12
